<!DOCTYPE html>
<html lang="es">
    <?php 
    include("cabecera.php");
    ?>
    <body>
    <?php 
    include("menu.php");
    ?>
    <main>
       <section id="miproyectoe"> 
        <article id="proyector">
            <p> <h4>Ciberseguridad</h4></p>
            <img id="iarticulo" src="imagenes/Particulo.jpg.png">
            <div style="text-align:justify">La historia del centro docente comienza con la evolución de las comunicaciones en la Policía Nacional las cuales dieron origen a la necesidad de capacitar al personal de la institución para la administración y mantenimiento de los diferentes equipos que para la época poseía en el año de 1955, seleccionaron 20 agentes para realizar el curso de radio voz en la estación 100 y entre los años de 1961 y 1974 llega al país una misión americana bajo el programa Alianza internacional para el desarrollo trayendo consigo cursos de formación técnica en coordinación con el SENA para oficiales suboficiales y agentes en aspectos como am FM y banda Blu en 1983 con la creación de la división de Comunicaciones y electrónica la Policía Nacional tomó la decisión de capacitar sus propios funcionarios a través de la sección de capacitación técnica de comunicaciones graduando 246 técnicos básicos en comunicaciones entre oficiales y suboficiales.<br>
                Camilo Ramírez jefe de ciberseguridad de Colombia conocido como C4 nos habla de la lucha contra el cibercrimen en Colombia unidad vio la necesidad de crear un canal de atención que le dijera a la ciudadanía que paso a paso debía seguir el evento en que recibiera un correo sospechoso Que pasó  a seguir el evento en que hubiese sido víctima de un delito que pudiese quizás afectar algún bien jurídico tutelado claramente, sin embargo ,para la época pues había una gran limitante es que si bien había un grupo de investigativo delitos informáticos, no se contaba aún con una ley de delitos informáticos hasta el año 2009 con la ley 1273,aquí podemos nosotros encontrar una ley que habla precisamente de la protección de la información y los datos Y también de unos delitos mencionados allí como atentados informáticos que son prácticamente que delitos de fraude fueron también Resaltar como se crea el equipo de atención de emergencias en ciencias cibernéticos en el año 2010, ahí vemos desde el año también 2011 una serie de lineamientos o políticas públicas vemos tres compis el primero de ellos el año 2011 que define alineamientos para efectos de ciberseguridad y ciberdefensa, allí se le da esa responsabilidad de ciberseguridad al centro cibernetico policial y la responsabilidad de la ciber defensa al comando.<br><br><img id="articulo" src="imagenes/articulo.jpg" >
                 Un año después vemos entonces también algunos aspectos relevantes como políticas públicas que definen ya la seguridad digital en Colombia que eventualmente pasan a hablar ya también de confianza y seguridad digital vemos Nosotros también como el convenio de Budapest es vinculado a nuestra legislación a través de la ley 1928, eso es lo que nos permite a nosotros precisamente tener un marco que nos avale a nosotros cooperación policial y Judicial con los países que hacen parte de este convenio sino también poder ser nosotros beneficiarios de intercambio de buenas prácticas experiencias exitosas entre otras cosas, finalmente resaltar como el Ministerio de defensa era concebido como un concepto que precisamente ese año se define como ese ser nacional dependiendo del Ministerio de las tecnologías de la información y también de las diferentes entidades y los diferentes actores, precisamente ese ecosistema de ciberseguridad conscientes de la necesidad de fortalecer las diferentes capacidades, permiten crear a través de una ley la dirección especializada de investigaciones delitos informáticos en la fiscalía general de la nación para hablar de Ciber criminalidad.<br><br>
                 Pues digamos que hay que hablar o empezar desde lo general y es la ciberseguridad, para efectos de ciberseguridad hay que hablar entonces de delitos cibernéticos o delitos informáticos de cibercrimen y esto digamos que es relevante en el sentido que su legislación contempla los delitos informáticos, sin embargo hay una división allí adentro y esto también digamos que lo menciona porque en algunas ocasiones se puede pensar que se está hablando de lo mismo, se puede pensar que de hecho un delito que no está afectando la información en los datos y que por lo tanto no es un delito informático, no obstante realmente lo es como un simple hurto celular , entonces como los delitos cibernéticos hacen referencia a la información y los datos como fin en otras palabras lo que se pretende afectar ese bien jurídico tutelado de la información y los datos, para dar algunos ejemplos de acuerdo a la legislación vemos el uso de software malicioso, vemos el acceso abusivo al sistema informático y el daño informático, estamos hablando de los primeros siete delitos cuando hablamos entonces de delitos informáticos estamos hablando del internet como un medio para afectar otro bien jurídico entretelado usualmente son delitos tradicionales, vemos nosotros entonces delitos de patrimonio económico que afecta la fe pública, la libertad el honor, los derechos morales patrimoniales de autor y los delitos de fraude que de hecho en nuestra ley contemplamos dos. También unos delitos informáticos que realmente tienen un impacto supremamente importante en la sociedad y puntualmente están vinculando encontramos delitos de propiedad intelectual, delitos de piratería informática, hábitos de contenido como materiales sexual infantil y delitos de fraude informático; precisamente nuestra ley ha sido digamos que coherente con esta normatividad internacional y los delitos que estaban contemplados son referenciados de esta norma expedidas del año 2009, una reingeniería que demanda que haya algunos tipos penales que se modifiquen y que haya también unos tipos penales adicionales que quizás algunas circunstancias se puedan replantear.<br>
                Actual se encuentran trabajando para crear el grupo de ciberseguridad recordemos que están enfocados en esa en esa parte pequeña de la lucha contra la cibercriminalidad para poder precisamente ampliar el portafolio de servicios, es por ello que sus funcionarios han sido capacitados por el FBI y por múltiples organizaciones internacionales, cuentan con una escuela de tecnologías de la información que hace parte de la dirección nacional de escuelas que tiene unos programas en materia de ciberseguridad y análisis de evidencia digital, donde pueden encontrar un lugar de los hechos y con unos protocolos de preservación obtener una durabilidad importante cuando hablamos de evidencia digital en el evento que lleguemos a un lugar de los hechos y encontremos por ejemplo la información o la evidencia de la memoria RAM si esta información no es recolectada de manera oportuna por parte de los investigadores, pues va a perderse sin ningún tipo de oportunidad para poder recuperarla.
            </div>
        </article>
        </section> 

        
        <aside> <!-- definimos el bloque del LADO DERECHO -->
            <p><h3>MATERIAS</h3></p>
             <ul id="barra">
                <li><a href="matematicas.php">MATEMATICAS</a></li>
                <li><a href="programacion.php">PROGRAMACION</a></li>
             <ul>
        </aside>
    </main>
        <footer> <!-- Finalizamos la estructura con el pie de la página -->
            <h4>.. power by SENA - CDAE 2019..</h4>
            </footer> 
 </body>
</html>